# Generated by Django 5.0.4 on 2024-04-25 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='UserAndKino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kino_id', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Actions',
            },
        ),
        migrations.CreateModel(
            name='Kino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('direction', models.TextField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.genre')),
            ],
            options={
                'verbose_name': 'Kino',
                'verbose_name_plural': 'Kinos',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('kinos', models.ManyToManyField(to='api.kino')),
            ],
            options={
                'verbose_name': 'Users',
            },
        ),
    ]
